version: '3'
services:
  smart-room:
    image: smart-room:latest
    build: .
    container_name: SMART_ROOM
    ports:
      - 5000:5000
    restart: always
    env_file: ./production_env

volumes:
  grafana-storage: