version: '3.4'
services:
  postgres:
    # checking connection: $ docker exec -it  DB_POSTGRES psql -U {POSTGRES_USER} -W {POSTGRES_DB}
    image: postgres:13.1-alpine
    container_name: DB_POSTGRES
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./services/sql/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ACCOUNT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis:6
    container_name: REDIS
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./services/grafana/:/etc/grafana/
      - grafana_data:/var/lib/grafana
    restart: always
  smart-room:
    image: docker.pkg.github.com/ncku-ccs/smart-room-backend/dev:latest
    build: .
    restart: always
    ports:
      - 5000:5000
    container_name: SMART_ROOM
    env_file: ./production_env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data
  grafana_data:
    name: grafana_data
