[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "$version"
changelog_incremental = true
update_changelog_on_bump = true
version_files = [
    "apiary.apib:API-version",
]

[tool.black]
line-length = 120
