"""empty message

Revision ID: 484ba956f0a7
Revises: faa4c3bed519
Create Date: 2021-01-23 17:57:27.731237

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '484ba956f0a7'
down_revision = 'faa4c3bed519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meter_data', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meter_data', type_='unique')
    # ### end Alembic commands ###
