"""empty message

Revision ID: 4c8f963b58f5
Revises: cb0eed9e4e3b
Create Date: 2021-02-17 13:41:24.917963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8f963b58f5'
down_revision = 'cb0eed9e4e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('location', sa.String(), nullable=False))
    op.drop_constraint('sensor_name_loc_key', 'sensor', type_='unique')
    op.create_unique_constraint(None, 'sensor', ['uuid'])
    op.create_unique_constraint(None, 'sensor', ['name', 'location'])
    op.drop_column('sensor', 'loc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('loc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sensor', type_='unique')
    op.drop_constraint(None, 'sensor', type_='unique')
    op.create_unique_constraint('sensor_name_loc_key', 'sensor', ['name', 'loc'])
    op.drop_column('sensor', 'location')
    # ### end Alembic commands ###
