"""empty message

Revision ID: 5646a21a9d9b
Revises: a06f40ddc0cf
Create Date: 2021-01-24 11:05:18.922741

"""
from alembic import op
import sqlalchemy as sa


# required if base_model or ModelMixin is used,
# so that utils.base_model's class can be referenced.
import sys
sys.path.insert(0, "./smart_room")
import utils

# revision identifiers, used by Alembic.
revision = '5646a21a9d9b'
down_revision = 'a06f40ddc0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', utils.base_models.UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', utils.base_models.UTCDatetime(), nullable=True),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'sensor_data', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
