"""empty message

Revision ID: 999d9af15a0b
Revises: 5646a21a9d9b
Create Date: 2021-01-24 15:32:11.895889

"""
from alembic import op
import sqlalchemy as sa


from models.utilities import UUID2STR, UTCDatetime

# revision identifiers, used by Alembic.
revision = '999d9af15a0b'
down_revision = '5646a21a9d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_record',
    sa.Column('uuid', UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', UTCDatetime(), nullable=True),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('device',
    sa.Column('uuid', UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', UTCDatetime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'gateway', ['token'])
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'gateway', type_='unique')
    op.drop_table('device')
    op.drop_table('control_record')
    # ### end Alembic commands ###
