"""empty message

Revision ID: a06f40ddc0cf
Revises: 484ba956f0a7
Create Date: 2021-01-23 20:44:59.624272

"""
from alembic import op
import sqlalchemy as sa

from models.utilities import UUID2STR, UTCDatetime

# revision identifiers, used by Alembic.
revision = 'a06f40ddc0cf'
down_revision = '484ba956f0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('uuid', UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', UTCDatetime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True, comment='C'),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('sensor', sa.String(), nullable=False, comment='sensor name'),
    sa.Column('gateway', sa.String(), nullable=False, comment='gateway name'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
