"""empty message

Revision ID: f9325c07f2a4
Revises: 4c8f963b58f5
Create Date: 2021-02-17 15:43:33.957570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9325c07f2a4'
down_revision = '4c8f963b58f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('location', sa.String(), nullable=False))
    op.drop_constraint('device_name_key', 'device', type_='unique')
    op.create_unique_constraint(None, 'device', ['name', 'location'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='unique')
    op.create_unique_constraint('device_name_key', 'device', ['name'])
    op.drop_column('device', 'location')
    # ### end Alembic commands ###
