"""empty message

Revision ID: faa4c3bed519
Revises: fb07906c8344
Create Date: 2021-01-22 21:35:48.995692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from models.utilities import UUID2STR, UTCDatetime


# revision identifiers, used by Alembic.
revision = 'faa4c3bed519'
down_revision = 'fb07906c8344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_data',
    sa.Column('uuid', UUID2STR(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created', UTCDatetime(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True, comment='V'),
    sa.Column('current', sa.Float(), nullable=True, comment='A'),
    sa.Column('power', sa.Float(), nullable=True, comment='W'),
    sa.Column('total_current', sa.Float(), nullable=True, comment='kWh'),
    sa.Column('sensor', sa.String(), nullable=False, comment='sensor name'),
    sa.Column('gateway', sa.String(), nullable=False, comment='gateway name'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('smart_meter')
    op.add_column('gateway', sa.Column('token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'gateway', ['uuid'])
    op.create_unique_constraint(None, 'gateway', ['name'])
    op.drop_column('gateway', 'bearer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway', sa.Column('bearer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gateway', type_='unique')
    op.drop_constraint(None, 'gateway', type_='unique')
    op.drop_column('gateway', 'token')
    op.create_table('smart_meter',
    sa.Column('uuid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('voltage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='V'),
    sa.Column('current', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='A'),
    sa.Column('power', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='W'),
    sa.Column('total_current', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='kWh'),
    sa.Column('sensor', sa.VARCHAR(), autoincrement=False, nullable=False, comment='sensor name'),
    sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=False, comment='gateway name'),
    sa.PrimaryKeyConstraint('uuid', name='smart_meter_pkey')
    )
    op.drop_table('meter_data')
    # ### end Alembic commands ###
